### ISSUE TITLE
Apktool nable to rebuild apk

### ISSUE THREAD

**Issue by Dj2o** [Hax4us/Apkmod#101]
1) W: /data/data/com.termux/files/usr/share/apkmod/root/.bind/original/res/values/attrs.xml:61: error: invalid value for type 'attr'. Expected a reference.
2) W: /data/data/com.termux/files/usr/share/apkmod/root/.bind/original/res/values/raws.xml:3: error: invalid value for type 'raw'. Expected a reference.

What happened?
![Screenshot_20201217-204316](https://user-images.githubusercontent.com/64633599/102504875-8df28a80-40ab-11eb-9a2f-20b5aab195d1.png)

**Comment by Hax4us** [comment]
can you give app or link of app in which you are binding

**Comment by Dj2o** [comment]
[Uploading Lite 227.0.0.5.115_259543278.apk.zip…]()

**Comment by Dj2o** [comment]
This is the app

https://play.google.com/store/apps/details?id=com.facebook.lite

**Comment by Hax4us** [comment]
@Dj2o no you can't bind with fb lite
