### ISSUE TITLE
Can't recompile => Exception in thread 

### ISSUE THREAD

**Issue by TheAbdul123** [Hax4us/Apkmod#105]
![Screenshot_20210201_223214](https://user-images.githubusercontent.com/78105315/106497646-23bd6a00-64e0-11eb-89cf-9bd2ff4872ac.jpg)

### **Problem:**
It recompiles almost till last and then shows _exception_. I am a newbie to termux so I don't know real issue. I have posted as screenshot.

### **Expected:**
I expected that the app will be moded by watching the video at https://youtu.be/ZDGOUfp09g8

### **Additional:**
**1. Terrmux-info :**
Packages CPU architecture:
aarch64
Subscribed repositories
### sourcelist
deb https://termux.org/packages/ stable main
### science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
### game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
### 

sources.list.d/termuxblack.list

deb https://hax4us.github.io/TermuxBlack/ termuxblack main
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.77+ #1 SMP PREEMPT Mon Nov 30 16:49:44 CST 2020 aarch64 Android
Device manufacturer:
vivo
Device model:
vivo 1823

**2. Apkmod version** (2.2)

**3. Original APK file:**
[GB Whatsapp](https://mega.nz/file/bkUSBZKb#6zeZfJsopQaoBN2dXhHLafZ9GSqqeFEDGf6r0BD1w8M)

**Comment by Hax4us** [comment]
Apkmod can bind GBWhatsApp but not all versions.
Tested one is http://www.mediafire.com/file/2ou3lpoc3ukpud6/GBWA.8.35_By_FouadMODS.apk/file

or you can try on any othet APP

**Comment by TheAbdul123** [comment]
Thank you sir!
Can I get link to the telegram channel?

**Comment by Hax4us** [comment]
t.me/hax4us_group
