### ISSUE TITLE
Problem in setting up

### ISSUE THREAD

**Issue by karansharmahr** [Hax4us/Apkmod#107]
I am facing this problem bro when I use setup the files like aapt are not downloading as u have deleted those from your website so I the tool doesn't work so fix this

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by Hax4us** [comment]
attach screenshot please

**Comment by Hax4us** [comment]
do `apkmod -u`
