### ISSUE TITLE
Couldn't find aapt binary executable

### ISSUE THREAD

**Issue by harshkuttu** [Hax4us/Apkmod#108]
![Screenshot_2021-02-08-17-15-55-705_com termux](https://user-images.githubusercontent.com/40667898/107215513-6972b900-6a31-11eb-8731-3c195fbad875.jpg)

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by Hax4us** [comment]
do `apkmod -u`
