### ISSUE TITLE
Apkmod cant bind

### ISSUE THREAD

**Issue by Advaithvp** [Hax4us/Apkmod#109]
Apkmod just won't bind APK. I am on android 9.1 stock ROM 2Gb ram. Its say can't bind apk.
[*] Binding /data/data/com.termux/files/home/mktr/test.apk
Using APK template: /data/data/com.termux/files/home/mktr/test.apk
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20210210-18673-vflb8h/original/AndroidManifest.xml
[!] can't bind, take screenshot and open a issue on github
I tried on another phone. It just doesn't work. I tried on a old phone with android version 7.0 still doesn't works.
I have installed all the required dependencies and it still won't work. I have also tested on a clean installation on termux.[](url)

**Comment by Hax4us** [comment]
do `apkmod -u` and attack all screenshots here

**Comment by Hax4us** [comment]
closing due to no response
