### ISSUE TITLE
I m not able to bind Payload with the help of apkmod

### ISSUE THREAD

**Issue by rohzsan** [Hax4us/Apkmod#122]
**Problem description**
![Screenshot_2021-04-02-23-24-31-92_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/81825962/113441272-a3e24c00-940b-11eb-9e84-dd4101e2e149.jpg)

A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
When i put commands it show error in screenshot... Because of changing command in metasploit which is "./msfvenom" replace with "ruby msfvenom" for creating payload... So, may be it impact of it.

**Comment by Pradeep-bana** [comment]
I have the same problem bro.

**Comment by Hax4us** [comment]
closing since its not a error.
make sure metasploit  installed and has wrapper `msfvenom` in `$PREFIX/bin` directory

**Comment by Pradeep-bana** [comment]
I can't understood bro

**Comment by Hax4us** [comment]
@Pradeep-bana error is pretty straightforward 
apkmod is unable to find `msfvenom` so install it through
https://GitHub.com/hax4us/Metasploit_termux

**Comment by Pradeep-bana** [comment]
I have installed it you can also see
