### ISSUE TITLE
Error: One or more options failed to validate: LHOST

### ISSUE THREAD

**Issue by sokal24sky** [Hax4us/Apkmod#123]
Give solution plz !!

![Screenshot_20210429-102602_Termux](https://user-images.githubusercontent.com/75323129/116502756-3a544100-a8d6-11eb-81b2-5cb38f7d483f.png)

**Comment by suryapravin12** [comment]
How you fix it

**Comment by suryapravin12** [comment]
Please tell me I also have this problem

**Comment by Nitho1526** [comment]
porfavor cual es la solucion a ese problema?
