### ISSUE TITLE
keytool not found

### ISSUE THREAD

**Issue by nichu8** [Hax4us/Apkmod#13]
sing APK template: /storage/emulated/0/n8.apk             Error: keytool not found. If it's not in your PATH, please add it.                                                    [!] Try again with -a option
But if still can't bind, take screenshot and open a issue on github
$
![Screenshot_20191021_081717](https://user-images.githubusercontent.com/50399699/67173074-3c813980-f3db-11e9-92bb-3c945935aafa.jpg)

**Comment by Hax4us** [comment]
It looks like setup script was not executed successfully. Run `setup.sh` script and this time take screenshots and give here
