### ISSUE TITLE
I can't bind

### ISSUE THREAD

**Issue by suryapravin12** [Hax4us/Apkmod#141]
![Uploading Screenshot_20211002-021237.jpg…]()

**Comment by suryapravin12** [comment]
![Screenshot_20211001-172744](https://user-images.githubusercontent.com/91659620/135729624-fb9270ff-7162-4c0c-a14c-85ffafbb7435.jpg)

**Comment by suryapravin12** [comment]
Ple help

**Comment by suryapravin12** [comment]
![Screenshot_20210930-132413](https://user-images.githubusercontent.com/91659620/135729652-c7a9a629-5679-4ac5-93b1-bca93a5122fb.jpg)

**Comment by Hax4us** [comment]
correct syntax is `apkmod -b -i INPUT.apk -o OUTPUT.apk lhost=? lport=?`
