### ISSUE TITLE
Unable to bind payload

### ISSUE THREAD

**Issue by vksgoenka1** [Hax4us/Apkmod#143]
When I try to bind payload with all right details this error Happen, how to solve this
![Screenshot_2021-11-28-11-47-54](https://user-images.githubusercontent.com/94369290/143732018-d71c92c8-bef4-4fc7-80ae-21f1f1c557a7.png)

**Comment by Hax4us** [comment]
Provide some details like output of `termux-info`  and also check if you can create simple payload with metasploit or not.

**Comment by vksgoenka1** [comment]
This is device information, now what I do to bind payload


![Uploading Screenshot_2021-11-28-12-03-41.png…]()

**Comment by hamza6552** [comment]
Plz fix 
![Uploading Screenshot_20220106-160336.png…]()

**Comment by Hax4us** [comment]
closing bcz of lack of information
