### ISSUE TITLE
Issue not resolved while building apk I am tried aapt & aapt2

### ISSUE THREAD

**Issue by Yallaraddi** [Hax4us/Apkmod#145]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.
![Screenshot_2021-12-24-21-23-34-165_com termux](https://user-images.githubusercontent.com/82775730/147363391-70c80b62-594e-4810-82d0-f1f2094e544d.jpg)

**Comment by Hax4us** [comment]
Metasploit must be installed before apkmod
