### ISSUE TITLE
[*] -i parameter missing, no input specified

### ISSUE THREAD

**Issue by mohittyagi11** [Hax4us/Apkmod#147]
I am getting below:

/apkmod.sh --signature-bypass --killer=k2 -i ./base.apk -o ./patched.apk
(standard_in) 1: illegal character: V
(standard_in) 1: illegal character: R
(standard_in) 1: illegal character: S
(standard_in) 1: illegal character: I
(standard_in) 1: illegal character: O
(standard_in) 1: illegal character: N
(standard_in) 1: parse error
./apkmod.sh: line 246: [: 1: unary operator expected
readlink: illegal option -- m
usage: readlink [-n] [file ...]
readlink: illegal option -- m
usage: readlink [-n] [file ...]
[*] -i parameter missing, no input specified

**Comment by Hax4us** [comment]
don't use script directly.
