### ISSUE TITLE
Unable to bind apk. Please resolve this.

### ISSUE THREAD

**Issue by maxx6668141** [Hax4us/Apkmod#150]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

![Screenshot_20220127-134126_Termux.jpg](https://user-images.githubusercontent.com/64184467/151318120-07e4ffe9-3056-4294-86fb-ff9d477562bb.jpg)

**Comment by Hax4us** [comment]
Can you give that app ?

**Comment by maxx6668141** [comment]
> Can you give that app ?

Truecaller: https://play.google.com/store/apps/details?id=com.truecaller

**Comment by maxx6668141** [comment]
> 
> 
> **Problem description**
> A clear and concise description of what the problem is. You may post screenshots in addition to description.
> 
> **Steps to reproduce**
> Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Additional information**
> 1. Post output of command `termux-info`
> 2. Post version `apkmod -v`
> 3. Attach Original __Apk__ file.
> 
> 
> ![Screenshot_20220127-134126_Termux.jpg](https://user-images.githubusercontent.com/64184467/151318120-07e4ffe9-3056-4294-86fb-ff9d477562bb.jpg)

I guess this was an issue of the app and not the tool. It did worked with other app, hence closing this. Thankyou
