### ISSUE TITLE
Number of arguments error

### ISSUE THREAD

**Issue by Vamshi3130** [Hax4us/Apkmod#17]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by Hax4us** [comment]
Update `apkmod -u` and try again

**Comment by Vamshi3130** [comment]
Tq sir for response
