### ISSUE TITLE
I can't decompile apps using apkmod

### ISSUE THREAD

**Issue by mikesew1320** [Hax4us/Apkmod#18]
I can't decomple apps using apkmod.

See the screenshot below👇

**Comment by Hax4us** [comment]
Where is screenshot ?

**Comment by Hax4us** [comment]
Closing for now, you can reopen it if error is still there

**Comment by mikesew1320** [comment]
Why you closed this issue?

I can't recompile apps after decompiling them.

For example I can decompile and recompile older apps like "IMEI Analyzer" but I can only decompile apps having newer app pattern like"Mixplorer". When I try to recompile them there is an error occurred when the tool reached the resources folder of them.

Please help me!

I can provide you the ss if u need

**Comment by mikesew1320** [comment]
Why you closed this issue?

I can't recompile apps after decompiling them.

For example I can decompile and recompile older apps like "IMEI Analyzer" but I can only decompile apps having newer app pattern like"Mixplorer". When I try to recompile them there is an error occurred when the tool reached the resources folder of them.

Please help me!

I can provide you the ss if u need

**Comment by mikesew1320** [comment]
Why you closed this issue?

I can't recompile apps after decompiling them.

For example I can decompile and recompile older apps like "IMEI Analyzer" but I can only decompile apps having newer app pattern like"Mixplorer". When I try to recompile them there is an error occurred when the tool reached the resources folder of them.

Please help me!

I can provide you the ss if u need

**Comment by Hax4us** [comment]
You didn't give any screenshot that's why I closed it so give screenshots this time please so that I can look forward

**Comment by mikesew1320** [comment]
> You didn't give any screenshot that's why I closed it so give screenshots this time please so that I can look forward

Please visit the new issue #24
