### ISSUE TITLE
Error: Unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by madukachsse** [Hax4us/Apkmod#20]
I get 'Error: Unable to rebuild apk with apktool' when binding payload to apk.

I have tried ' -a -b ' i still get the same error.
![Screenshot_20191127-020253](https://user-images.githubusercontent.com/43529402/69685096-78cf4600-10bb-11ea-9cee-42b6705c98c0.png)
![Screenshot_20191127-020300](https://user-images.githubusercontent.com/43529402/69685103-81c01780-10bb-11ea-9acd-94229068d0a8.png)

**Comment by Hax4us** [comment]
What's  output of `termux-info`

**Comment by madukachsse** [comment]
![Screenshot_20191202-135956](https://user-images.githubusercontent.com/43529402/69961443-2e5f2680-150c-11ea-91e8-988bb1eb2c70.png)

**Comment by madukachsse** [comment]
Although it works with old apk. Most current application does not work.

**Comment by Hax4us** [comment]
I asked for all screenshots of binding process , bcz some of them are missing

**Comment by madukachsse** [comment]
Here is all screenshot of binding process

**Comment by madukachsse** [comment]
![Screenshot_20191203-190117](https://user-images.githubusercontent.com/43529402/70076967-2b456280-1600-11ea-93a1-f2e8edb7ce2c.png)

**Comment by madukachsse** [comment]
![Screenshot_20191203-190224](https://user-images.githubusercontent.com/43529402/70076988-36988e00-1600-11ea-9ad8-26fc751c2a6e.png)

**Comment by madukachsse** [comment]
![Screenshot_20191203-190307](https://user-images.githubusercontent.com/43529402/70077010-3f895f80-1600-11ea-8cd5-ed89e886ebb8.png)

**Comment by madukachsse** [comment]
![Screenshot_20191203-190518](https://user-images.githubusercontent.com/43529402/70077027-487a3100-1600-11ea-951a-cabaf6817183.png)

**Comment by madukachsse** [comment]
![Screenshot_20191203-190526](https://user-images.githubusercontent.com/43529402/70077043-52039900-1600-11ea-9292-c8219b12e5fc.png)

**Comment by madukachsse** [comment]
Name of app is buzzbreake. All most all the app i tried didnt work. Only works on uc mini.

**Comment by madukachsse** [comment]
Link to application on google playstore

https://play.google.com/store/apps/details?id=news.buzzbreak.android

**Comment by madukachsse** [comment]
You can also try it on any of this applications

https://play.google.com/store/apps/details?id=com.requapp.requ

https://play.google.com/store/apps/details?id=com.bigtoken.consumer

https://play.google.com/store/apps/details?id=com.tvtwo.highest.paying.cash.app.make.money.surveys.rewards.free.income

https://play.google.com/store/apps/details?id=com.cashmaniac.app

**Comment by Hax4us** [comment]
@madukachsse ok I got it what's going wrong , I will fix it asap

**Comment by madukachsse** [comment]
Ok bro. Looking forward to it

**Comment by madukachsse** [comment]
Fixed yet???

**Comment by Hax4us** [comment]
Now try `apkmod -a -b ...` ( don't forget to add `-a` option)

**Comment by madukachsse** [comment]
Its still not working

**Comment by madukachsse** [comment]
I told you earlier in the conversation that i have tried using (apkmod -a -b ...). And now you ask me to try again without update to the package?

**Comment by madukachsse** [comment]
I tried again, Am still getting the same error

**Comment by madukachsse** [comment]
![Screenshot_20191207-091724](https://user-images.githubusercontent.com/43529402/70371472-b316bf80-18d3-11ea-93c6-840db358b060.png)

![Screenshot_20191207-091826](https://user-images.githubusercontent.com/43529402/70371478-c2960880-18d3-11ea-9fd2-db9fd03cecc9.png)

![Screenshot_20191207-092102](https://user-images.githubusercontent.com/43529402/70371482-d0e42480-18d3-11ea-9494-61b5abf17a63.png)
![Uploading Screenshot_20191207-092128.png…]()

**Comment by madukachsse** [comment]
![Screenshot_20191207-092128](https://user-images.githubusercontent.com/43529402/70371519-3f28e700-18d4-11ea-965a-f930c45979b8.png)

**Comment by madukachsse** [comment]
Did you successfully bind any of app i sent you the link?

**Comment by Hax4us** [comment]
> Did you successfully bind any of app i sent you the link?

Yes buzz.apk binded successfully

**Comment by madukachsse** [comment]
So i should use 
apkmod -u -a -b... ?

**Comment by madukachsse** [comment]
After using ( apkmod -u ), to update apkmod, the app buzz.apk still not binding

**Comment by madukachsse** [comment]
![Screenshot_20191207-103316](https://user-images.githubusercontent.com/43529402/70372321-b9aa3480-18dd-11ea-9612-d20f099be645.png)
![Uploading Screenshot_20191207-103401.png…]()
![Uploading Screenshot_20191207-103339.png…]()
![Uploading Screenshot_20191207-103301.png…]()
![Uploading Screenshot_20191207-103239.png…]()
![Uploading Screenshot_20191207-103413.png…]()

**Comment by madukachsse** [comment]
![Screenshot_20191207-103301](https://user-images.githubusercontent.com/43529402/70372345-fe35d000-18dd-11ea-87d1-e5fe73b4e860.png)

**Comment by madukachsse** [comment]
![Screenshot_20191207-103316](https://user-images.githubusercontent.com/43529402/70372347-068e0b00-18de-11ea-90ef-0742e9c85250.png)
![Screenshot_20191207-103339](https://user-images.githubusercontent.com/43529402/70372353-0d1c8280-18de-11ea-8bd8-f841def1e4e7.png)

**Comment by madukachsse** [comment]
![Screenshot_20191207-103401](https://user-images.githubusercontent.com/43529402/70372361-1a397180-18de-11ea-9b79-5a79c4617cae.png)
![Screenshot_20191207-103413](https://user-images.githubusercontent.com/43529402/70372364-202f5280-18de-11ea-9436-6f2466dae341.png)

**Comment by Hax4us** [comment]
How did u install metasploit ?

**Comment by madukachsse** [comment]
Through unstable-repo

**Comment by madukachsse** [comment]
See where rebuilding error, shows unable to rebuild apk using apktool

**Comment by Hax4us** [comment]
> Through unstable-repo

Well I tested your app with metasploit from my script so I will again test it with unstable-repos metasploit

**Comment by madukachsse** [comment]
Ok

**Comment by madukachsse** [comment]
Hello. I didn't hear from you again

**Comment by madukachsse** [comment]
I had more success Binding payload to apk, after installing metasploit from your script. Thanks

**Comment by Kamilhoo** [comment]
Sir where output APK of apkmod store?
