### ISSUE TITLE
Error: Malformed version number string Error: Invalid or corrupt jarfile /opt/apktool.jar

### ISSUE THREAD

**Issue by saeedo201** [Hax4us/Apkmod#21]
![Screenshot_20191129-143541](https://user-images.githubusercontent.com/44009760/69869558-dd55f500-12b5-11ea-82f4-03d4c03050db.jpg)
how i can resolve this mistake please.

**Comment by Hax4us** [comment]
Can you post output of `apktool -version`

**Comment by Hax4us** [comment]
Closing as lack of information
