### ISSUE TITLE
Could not locate gemfile

### ISSUE THREAD

**Issue by stefanosstef** [Hax4us/Apkmod#23]
![Screenshot_2019-12-27-11-07-09-892_com termux](https://user-images.githubusercontent.com/57360288/71510990-69e5da00-2899-11ea-8cbd-0ab6f1d298cf.jpg)
![Screenshot_2019-12-27-11-07-17-112_com termux](https://user-images.githubusercontent.com/57360288/71510996-779b5f80-2899-11ea-926a-02129a7a6def.jpg)
![Screenshot_2019-12-27-11-07-25-486_com termux](https://user-images.githubusercontent.com/57360288/71511014-841fb800-2899-11ea-9a2b-e963faf9c2a6.jpg)
![Screenshot_2019-12-27-11-07-31-322_com termux](https://user-images.githubusercontent.com/57360288/71511027-913ca700-2899-11ea-805f-1622f85a7b3e.jpg)
![Screenshot_2019-12-27-11-07-38-690_com termux](https://user-images.githubusercontent.com/57360288/71511047-a0bbf000-2899-11ea-8362-0e9f7a062d28.jpg)
![Screenshot_2019-12-27-11-07-44-925_com termux](https://user-images.githubusercontent.com/57360288/71511066-b3cec000-2899-11ea-8a87-bd46c573e56f.jpg)
![Screenshot_2019-12-27-11-08-17-800_com termux](https://user-images.githubusercontent.com/57360288/71511086-c34e0900-2899-11ea-940b-af97520e0a57.jpg)

**Comment by Hax4us** [comment]
Do this
`cd $HOME/metasploit-framework && bundle install`

**Comment by stefanosstef** [comment]
Thanks, that solved it but now I get this:
![Screenshot_2019-12-27-21-41-12-472_com termux](https://user-images.githubusercontent.com/57360288/71530313-df7d9480-28f1-11ea-97b2-b3221437a973.jpg)

Bind failed so it asked to try with aapt2 but I can't pass the -a parameter.I tried putting it before -b and after -b and it doesn't seem to take it.

**Comment by Hax4us** [comment]
can you run again but like this
```
sh -x $(which apkmod) -a -b /sdcard/download/Hond.apk -o tmp.apk lhost=127.0.0.1 lport=4444
```
And give screenshot

**Comment by stefanosstef** [comment]
Looks like it takes the -a parameter but fails anyway.I tried with 2 different apks, one I build using appsgeyser and one I extracted from installed app in my phone using myappsharer.

![Screenshot_2019-12-28-14-38-27-464_com termux](https://user-images.githubusercontent.com/57360288/71543840-62e5c700-2980-11ea-84d3-b3067ffc683a.jpg)
![Screenshot_2019-12-28-14-38-50-606_com termux](https://user-images.githubusercontent.com/57360288/71543841-68dba800-2980-11ea-9fd3-8aa53e340683.jpg)
![Screenshot_2019-12-28-14-39-02-314_com termux](https://user-images.githubusercontent.com/57360288/71543842-6f6a1f80-2980-11ea-8739-7e434d3a47d5.jpg)

**Comment by stefanosstef** [comment]
I will try tomorrow manually using apk easy tool

**Comment by Hax4us** [comment]
did you also install metasploit from unstable-repo ?

**Comment by K-Yasar-Arafath** [comment]
> Do this
> ```
> cd $HOME/metasploit-framework && bundle install
> ```

Thanks sir it's working 💪

**Comment by piuem** [comment]
An error occurred while installing racc (1.6.0), and Bundler
cannot continue.
Make sure that `gem install racc -v '1.6.0' --source
'https://rubygems.org/'` succeeds before bundling 


que hago con esto

**Comment by Lakhdarghemam24** [comment]
What's the solution
