### ISSUE TITLE
Still the aapt binary should need further modifications

### ISSUE THREAD

**Issue by mikesew1320** [Hax4us/Apkmod#24]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

------> It still have issue when trying to recompile some apps after successfully decompiling them like Magisk Manager. There is an issue that prohibit the app from being recompiled successfully!
![Screenshot_20191229-075732](https://user-images.githubusercontent.com/43565227/71556245-fd104280-2a46-11ea-9443-b89ae48b8d8f.jpg)

 ++++See the screenshot below 👇👇

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by Hax4us** [comment]
What's the name of app in which you are trying to bind payload ?

**Comment by mikesew1320** [comment]
> What's the name of app in which you are trying to bind payload ? Is it magisk manager ?

I am not trying to bind payload, I am trying to re-compile the app after modifications using Apkmod. That's all

**Comment by mikesew1320** [comment]
I can't show it from the source from what I typed b/c termux by default takes me automatically to the Bottom.

I think this issue is still caused by the resources folder inside the app.

**Comment by Hax4us** [comment]
Ok then what's the name of app ? I will test it on my device

**Comment by mikesew1320** [comment]
> Ok then what's the name of app ? I will test it on my device

It's Magisk Manager(From latest canary). You can found on the link below.👇

https://github.com/topjohnwu/magisk_files/tree/canary

Named "app-release.apk"
Btw I tried with another app "Smartpack Kernel Manager" I faced the same issue like what I faced for Magisk Manager. You can see on the screenshot below 👇

I think the tool has issue with open source apps. Ha...Ha.... JFF
![Screenshot_20191229-132259](https://user-images.githubusercontent.com/43565227/71577042-b9c7d980-2b03-11ea-8a98-a7b3fbfe7cbc.jpg)
![Screenshot_20191229-132309](https://user-images.githubusercontent.com/43565227/71577057-c6e4c880-2b03-11ea-83d1-fec9e59ddffe.jpg)
![Screenshot_20191229-132318](https://user-images.githubusercontent.com/43565227/71577066-d06e3080-2b03-11ea-914b-55552c16e9dc.jpg)

**Comment by mikesew1320** [comment]
> Ok then what's the name of app ? I will test it on my device

It's Magisk Manager(From latest canary). You can found on the link below.👇

https://github.com/topjohnwu/magisk_files/tree/canary

Named "app-release.apk"
Btw I tried with another app "Smartpack Kernel Manager" I faced the same issue like what I faced for Magisk Manager. You can see on the screenshot below 👇

I think the tool has issue with open source apps. Ha...Ha.... JFF
![Screenshot_20191229-132259](https://user-images.githubusercontent.com/43565227/71577042-b9c7d980-2b03-11ea-8a98-a7b3fbfe7cbc.jpg)
![Screenshot_20191229-132309](https://user-images.githubusercontent.com/43565227/71577057-c6e4c880-2b03-11ea-83d1-fec9e59ddffe.jpg)

**Comment by mikesew1320** [comment]
> > Ok then what's the name of app ? I will test it on my device
> 
> It's Magisk Manager(From latest canary). You can found on the link below.
> 
> https://github.com/topjohnwu/magisk_files/tree/canary Named "app-release.apk"
> 
> Btw, I tried with another app "Smartpack Kernel Manager" latest version 9.3. You can find on the link below 
> 
> https://github.com/SmartPack/SmartPack-Kernel-Manager/releases
> 
> I faced the same issue like what I faced for Magisk Manager. You can see on the screenshots below 
> 
> I think the tool has issue with open source apps. Ha...Ha.... JFF
> ![Screenshot_20191229-132259](https://user-images.githubusercontent.com/43565227/71577042-b9c7d980-2b03-11ea-8a98-a7b3fbfe7cbc.jpg)
> ![Screenshot_20191229-132309](https://user-images.githubusercontent.com/43565227/71577057-c6e4c880-2b03-11ea-83d1-fec9e59ddffe.jpg)

![Screenshot_20191229-132318](https://user-images.githubusercontent.com/43565227/71577498-6e162f80-2b05-11ea-9159-a0faaf7b44dd.jpg)

**Comment by Hax4us** [comment]
Ok now update apkmod by `apkmod -u`
I successfully decompile and recompile smartPack kernel manager app but Magisk Manager can't recompile , maybe they are using some kind of reverse engineering protection , same as Facebook WhatsApp etc ( most famous apps)

**Comment by mikesew1320** [comment]
Ok, I will update and try the result. 

They don't need to add such like features b/c the app is open source so anyone with an interest can made his own modded version.

From my point of view it's happened b/c of the file names found in the resources folder of the app(Too many files)

**Comment by Hax4us** [comment]
> From my point of view it's happened b/c of the file names found in the resources folder of the app(Too many files)

It makes sense

**Comment by mikesew1320** [comment]
> > From my point of view it's happened b/c of the file names found in the resources folder of the app(Too many files)
> 
> It makes sense

👍 Moved to Telegram!
