### ISSUE TITLE
How to properly use the -a command?

### ISSUE THREAD

**Issue by mikesew1320** [Hax4us/Apkmod#25]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

-------> I tried to recompile the app using aapt 2 binary and I need to use the command -a but it doesn't helped me, gives an error or no response at all.

-------> I entered like those Below 👇
     Apkmod -r -a /path1 -o /path2.apk
     Apkmod -a /path1 -o /path2.apk
     Apkmod -a -r /path1 -o /path2.apk

-------> Also I have one question for u, Why you don't update the Apktool to the latest version 2.4.1 ? It still shows 2.4.0 on the console. If u updated it to 2.4.1 then why this happened?
**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by Hax4us** [comment]
Oops I just enabled aapt2 only for binding and forget to add aapt2 flag for separate recompiling
Thanks for pointing it , I will fix it ASAP

**Comment by mikesew1320** [comment]
> Oops I just enabled aapt2 only for binding and forget to add aapt2 flag for separate recompiling
> Thanks for pointing it , I will fix it ASAP
> 
> No I did not update apktool but I will update it

Thanks! You are Great!
Making the update takes longer time? I am not asking for ETA, just to know. If you feel bad, Sorry!!

BTW I want to be near the development of this tool. Do u have a Telegram Group or Account? If u need we can talk more and make this tool awesome and stable than the current state. You can find me using @Mikesew1320 on Telegram or just you can give me your address.

Again thanks for ur great idea!

**Comment by Hax4us** [comment]
Correct way is `apkmod -ar appfolder -o app.apk` 
And check your telegram

**Comment by mikesew1320** [comment]
> Correct way is `apkmod -ar appfolder -o app.apk` or `apkmod -a -r appfolder -o app.apk`
> And check your telegram

Ok, Thanks!👍 Let me check it.....
