### ISSUE TITLE
How to resolve?!

### ISSUE THREAD

**Issue by SpartanT269** [Hax4us/Apkmod#28]
**How to solve it ?!**

![WhatsApp Image 2020-01-13 at 16 02 08](https://user-images.githubusercontent.com/35842155/72288219-f1b04000-361e-11ea-87b1-3488534d431f.jpeg)

**Comment by SpartanT269** [comment]
??!!

**Comment by Hax4us** [comment]
How did you install metasploit ?

**Comment by SpartanT269** [comment]
I had it installed by "pkg install metasploit", but then I used "https://github.com/Hax4us/Metasploit_termux", and a similar error popped up that said I couldn't move Termux-Apline.sh if you don't tell me the memory I think that was it

**Comment by SpartanT269** [comment]
ok i will install again !! install metasploit or apkmod first!

**Comment by SpartanT269** [comment]
![WhatsApp Image 2020-01-15 at 16 47 25](https://user-images.githubusercontent.com/35842155/72470272-e3952780-37b6-11ea-9f9c-0464c83bea30.jpeg)

**here is the screenshot**

**Comment by Hax4us** [comment]
So this is the problem. Do `apkmod -u` for reinstalling alpine

**Comment by SpartanT269** [comment]
Still Still Having the Same Error While Running "apktool -version"

**Comment by SpartanT269** [comment]
![WhatsApp Image 2020-01-16 at 08 35 32](https://user-images.githubusercontent.com/35842155/72525758-44feda00-383b-11ea-9870-60713cbd7877.jpeg)

**Look how it looks**

**Comment by Hax4us** [comment]
Please give screenshots ( all ) after `apkmod -u`

**Comment by SpartanT269** [comment]
![WhatsApp Image 2020-01-16 at 11 53 26](https://user-images.githubusercontent.com/35842155/72540273-037c2800-3857-11ea-8f74-bd3b43f3bc44.jpeg)
![WhatsApp Image 2020-01-16 at 11 53 26 (1)](https://user-images.githubusercontent.com/35842155/72540291-07a84580-3857-11ea-8105-211c95e2bb69.jpeg)
![WhatsApp Image 2020-01-16 at 11 53 26 (2)](https://user-images.githubusercontent.com/35842155/72540307-0b3bcc80-3857-11ea-83cb-b7f9d8d6d0ee.jpeg)
![WhatsApp Image 2020-01-16 at 11 53 26 (3)](https://user-images.githubusercontent.com/35842155/72540326-0ecf5380-3857-11ea-81b5-33db5e0bff42.jpeg)
![WhatsApp Image 2020-01-16 at 11 53 26 (4)](https://user-images.githubusercontent.com/35842155/72540342-11ca4400-3857-11ea-99f9-a48343aa36bc.jpeg)
![WhatsApp Image 2020-01-16 at 11 53 26 (5)](https://user-images.githubusercontent.com/35842155/72540364-15f66180-3857-11ea-93c4-14760dc86c1b.jpeg)
![WhatsApp Image 2020-01-16 at 11 53 26 (6)](https://user-images.githubusercontent.com/35842155/72540372-18f15200-3857-11ea-8de7-24001d5615c6.jpeg)

**Comment by SpartanT269** [comment]
do i need to have **JRE** installed ?!

**Comment by Hax4us** [comment]
> do i need to have **JRE** installed ?!

No

**Comment by SpartanT269** [comment]
**screenshots are up there**

**Comment by Hax4us** [comment]
Thanks for reporting this issue and now u can do `apkmod -u` and issue should be solved now

**Comment by SpartanT269** [comment]
doesn't work yet, I've already run **apkmod -u**

**Comment by Hax4us** [comment]
> doesn't work yet, I've already run **apkmod -u**

Then do Again and give new screenshots

**Comment by SpartanT269** [comment]
pelo o notei as mesmas coisas que a imagem acima

**Comment by SpartanT269** [comment]
well ... seems to me to appear the same things as the screenshot above

**Comment by SpartanT269** [comment]
??!!

**Comment by SpartanT269** [comment]
No solution?

**Comment by Hax4us** [comment]
> well ... seems to me to appear the same things as the screenshot above

I asked for screenshots

**Comment by SpartanT269** [comment]
![Screenshot_20200117-131731](https://user-images.githubusercontent.com/35842155/72632051-d5b4e300-392b-11ea-969a-320ddca899cc.jpg)
![Screenshot_20200117-131726](https://user-images.githubusercontent.com/35842155/72632052-d5b4e300-392b-11ea-82bb-82235a70e8cc.jpg)
![Screenshot_20200117-131748](https://user-images.githubusercontent.com/35842155/72632054-d5b4e300-392b-11ea-9174-873a5786c916.jpg)
![Screenshot_20200117-131739](https://user-images.githubusercontent.com/35842155/72632058-d64d7980-392b-11ea-96b6-fa49967f2db8.jpg)
![Screenshot_20200117-131712](https://user-images.githubusercontent.com/35842155/72632059-d6e61000-392b-11ea-911e-57b17d3a39ba.jpg)
![Screenshot_20200117-131704](https://user-images.githubusercontent.com/35842155/72632062-d6e61000-392b-11ea-9f02-75aad94e45b2.jpg)
![Screenshot_20200117-131718](https://user-images.githubusercontent.com/35842155/72632064-d6e61000-392b-11ea-9606-8c0e986e7ac0.jpg)

**Comment by Hax4us** [comment]
I fixed it now , u can do again `apkmod -u`

**Comment by SpartanT269** [comment]
I believe that everything is ok now

**Comment by SpartanT269** [comment]
thank you very much, thank you very much, may God bless you very much brother
