### ISSUE TITLE
Storing aapt archives in repository

### ISSUE THREAD

**Issue by oxr463** [Hax4us/Apkmod#31]
Source: https://github.com/Hax4us/Apkmod/blob/master/setup.sh#L61

**Comment by oxr463** [comment]
See: https://developer.android.com/studio/command-line/aapt2#download_aapt2

**Comment by oxr463** [comment]
Source: https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/tools/aapt2

**Comment by Hax4us** [comment]
What's the benifit ?

**Comment by oxr463** [comment]
There are multiple benefits:

- You no longer have to maintain this in the repository, i.e., updating for each new version.
- Repository size will be reduced, (See: https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git).
- Trust. As a user, how can I verify that what you are presenting to me is a non-modified copy of upstream?

Along with that, I would also recommend using a sha256sum or md5sum to ensure the integrity of the archive.

**Comment by Hax4us** [comment]
Done, thanks
