### ISSUE TITLE
Proot error

### ISSUE THREAD

**Issue by swapplays31** [Hax4us/Apkmod#32]
Someone please educate me on this error

$ apkmod -d /storage/emulated/0/Minecraft_1.14.1.5.apk -o /storage/emulated/0/vivoDownloadEx
[*] Decompiling /storage/emulated/0/Minecraft_1.14.1.5.apk
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/share/TermuxAlpine, cwd = /data/data/com.termux/files/home, $PATH=(null))
fatal error: see `proot --help`.
[*] Decompiled into /storage/emulated/0/vivoDownloadEx

**Comment by Hax4us** [comment]
As i can see installation was not completed so reinstall by `apkmod -u` and give all screenshots for investigation

**Comment by rashiqekk123** [comment]
![Screenshot_2020-04-12-05-20-36-640_com termux](https://user-images.githubusercontent.com/41786895/79057312-c1a82580-7c7d-11ea-98c9-81c7abfcf0da.jpg)
 
  Whats the error ...how to fix

**Comment by Hax4us** [comment]
@rashiqekk123 it's app specific issue

**Comment by kekebaby** [comment]
Can it be installed on Kali?
