### ISSUE TITLE
@Hax4us Apkmod needs an urgent fix!!!!

### ISSUE THREAD

**Issue by Mikesew1320** [Hax4us/Apkmod#34]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

###Can't install Alpine...... Just see the screenshots below for more detail.
![Screenshot_20200306-035413](https://user-images.githubusercontent.com/43565227/76081363-fd363c80-5fb9-11ea-9201-e74d5f547112.jpg)
![Screenshot_20200306-035342](https://user-images.githubusercontent.com/43565227/76081380-06bfa480-5fba-11ea-855d-dc572d48b21d.jpg)

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by hafizaliusama** [comment]
![IMG-20200513-WA0038](https://user-images.githubusercontent.com/58119673/82132356-56abba80-97f8-11ea-97a7-355c09a6fb61.jpg)
