### ISSUE TITLE
Unable to build apk

### ISSUE THREAD

**Issue by ragis0610** [Hax4us/Apkmod#36]
I tired everything with -a -b and also with apkmod-u. Still cant bind. 
![Screenshot_2020-04-09-07-06-23-63_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/62333459/78870409-b2e62680-7a63-11ea-82cb-0727eec4382a.png)

**Comment by Hax4us** [comment]
Somehow `_JAVA_OPTIONS` variable was set by any script ( i think you installed java separately from somewhere ) 
So unset this variable by `unset _JAVA_OPTIONS` then use apkmod
