### ISSUE TITLE
Unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by rashiqekk123** [Hax4us/Apkmod#38]
![Screenshot_2020-04-12-05-20-36-640_com termux](https://user-images.githubusercontent.com/41786895/79057350-38ddb980-7c7e-11ea-8709-41a16565f164.jpg)

 How to fix..

**Comment by Hax4us** [comment]
What is app name ?

**Comment by rashiqekk123** [comment]
> What is app name ?

Apkmod tool

**Comment by rashiqekk123** [comment]
![Screenshot_2020-04-12-05-20-41-748_com termux](https://user-images.githubusercontent.com/41786895/79061903-8f64eb00-7cb2-11ea-84d9-d300ebf4f5f9.jpg)

**Comment by Hax4us** [comment]
> > What is app name ?
> 
> Apkmod tool

I meant what is name of android application in which you are trying to bind payload

**Comment by Hax4us** [comment]
Closing since no response and also issue seems to be a app specific
