### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by dragos-olaru** [Hax4us/Apkmod#39]
The binded apk doesn't have all the payload permissions and if i use for example webcam_snap in msfconsole it says "Operation failed: 1" because the apk doesn't have that permission. Please fix this fast.

**Comment by Hax4us** [comment]
I got it and a new feature ( `enable permissions` ) will be available soon in next release i.e version 1.9

**Comment by Hax4us** [comment]
Update your apkmod by `apkmod -u` and then you can use New option `--enable-perm` for usage read this

**Comment by dragos-olaru** [comment]
Thank you
