### ISSUE TITLE
It's possible to run aapt2 (musl-libc) on kali

### ISSUE THREAD

**Issue by whoiam1337** [Hax4us/Apkmod#43]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

hi, your work is awesome, your tool is running perfectly, but I have a question, is it possible this aapt2 in tools can run on kali ?

this is aapt2 (aarch64)
aapt2: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, with debug_info, not stripped

I have tried to install the MUSL library on kali but still have errors when I run this aapt2.

this is error log 
 [aapt2.log](https://pastebin.com/ayd4fT59) 

Sorry for my bad English

**Comment by Hax4us** [comment]
You will have to place all libraries ( get from my tar file of aapt ) in `/usr/lib` and install a package `apk add protobuf`
