### ISSUE TITLE
apkmod doesn't work, can't decompile any apk and can't binding (termux)

### ISSUE THREAD

**Issue by hichemkanon** [Hax4us/Apkmod#44]
Hello guys there's problem with apkmod it can decomplile nor binding 
i dont know what is the problem 
but im asking for help or for solution if possible 
thanks

this is the picture of the issue :
https://filebin.net/3x9zh5qjy1bryr3m/Capture.PNG?t=0werp4u1

**Comment by Hax4us** [comment]
do `apkmod -u` and then give screenshots of all things

**Comment by hichemkanon** [comment]
<img src="https://filebin.net/1q75f00m9925sa9x/96347403_927487154360694_8003270341726044160_n.png?t=srtcii31">

<img src="https://filebin.net/atmi4ilpyzw0xjxh/96235241_896023840869257_5485351811759996928_n.png?t=l9kokqra">

<img src="https://filebin.net/mcrjr4nvqn37wjgr/95865196_757162281481915_46172010828529664_n.png?t=6171b4h4">

<img src="https://filebin.net/f7qspfgy1htadp9m/96516031_190918635257826_4327078034872991744_n.png?t=i2ndq1wm"> 

<img src="https://filebin.net/f7qspfgy1htadp9m/j.png?t=dm2axsf5">

<img src="https://filebin.net/f7qspfgy1htadp9m/2.png?t=m3uf63bm">

<img src="https://filebin.net/f7qspfgy1htadp9m/3.png?t=36vzvcw4">

<img src="https://filebin.net/f7qspfgy1htadp9m/final.png?t=h4d2a31u">

**Comment by Hax4us** [comment]
I can't see screenshots except first two

**Comment by hichemkanon** [comment]
ok i give you link directly show all

**Comment by hichemkanon** [comment]
this is the folder of screenshots :

https://mega.nz/folder/LrInkAZL#gp28bE0pv0Ld49iy6e0FIA

Brother ! after the update you gave me "apkmod -u"
now the tool is decompiling the original apk, before wasn't take wile time but now i think it is working 
I'm waiting the result

**Comment by Hax4us** [comment]
Let me know your results

**Comment by hichemkanon** [comment]
unfortunately brother
after waiting all this time the result is :
"Try again with -a option
But if still can't bind, take screenshot and open a issue on github"

i tried with -a 

this screenshot :

<img src="https://filebin.net/0z2287mg75chtih9/Screenshot_20200508-150918.png?t=vfgh4yvc">

<img src="https://filebin.net/t2clhum5bfdkt171/Screenshot_20200508-151306.png?t=hc0x6mxr">

**Comment by Hax4us** [comment]
Still i can't see your screenshots

**Comment by hichemkanon** [comment]
sorry brother 
this the first screenshot 
https://filebin.net/h8g14vgaiiic24f9/96233409_243350210070406_6650410511693250560_n.png?t=od5vpwfc

and this the second ;
https://filebin.net/h8g14vgaiiic24f9/2.png?t=fn1owtsu

**Comment by Hax4us** [comment]
Facebook can't be bind. Apkmod is working fine.
Some apps can't be bind with Payload specially popular apps like whatsapp fb insta telegram twitter etc

**Comment by hichemkanon** [comment]
ah !
ok brother thanks so much for your help 
i will re-try with another apps

**Comment by hichemkanon** [comment]
brother 
the problem is because this issue :

Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/share/TermuxAlpine/root/.bind/original/AndroidManifest.xml

this always appear before the tool finishing the work
always say couldn't find this file androidmanifest.xml


any solution for this ??
can i creat manually this file or something else ?
