### ISSUE TITLE
Directory is deleted if exists already

### ISSUE THREAD

**Issue by hichemkanon** [Hax4us/Apkmod#45]
when i want to decompile file apk i wrote this 

apkmod -d /sdcard/notepad.apk -o /sdcard

every file and folder is deleted from sdcard and from $HOME termux 

it stay only what is installed in phone and termux

!!!!!

**Comment by Hax4us** [comment]
Screenshots ?

**Comment by HaroldLimad** [comment]
It also happened to me, it deletes everything from the internal storage, the solution is = you must save what you decompile in a new folder example apkmod -d /sdcard/app.apk -o / sdcard / newfolder

**Comment by Hax4us** [comment]
Ahh i got it https://github.com/Hax4us/Apkmod/blob/8954287c4e2d7e0e9b2c44741c1ccce576dfe11e/apkmod.sh#L90 here i used `-f` hence output directory ( if exists already ) will be wiped out. Well i will remove it and let user to decide that if he wants to delete the output directory ( if already exist) and if directory is not present then will be created

**Comment by Hax4us** [comment]
closes with https://github.com/Hax4us/Apkmod/commit/a3059c824fcebf34392e067f2e45fa98c555e90b
