### ISSUE TITLE
storage permission not available

### ISSUE THREAD

**Issue by HaroldLimad** [Hax4us/Apkmod#46]
storage permission not available mybinded

**Comment by Hax4us** [comment]
Explain please

**Comment by HaroldLimad** [comment]
storage permission is not available in the app with added payload
![Screenshot_2020-05-14-09-02-19-260_com google android packageinstaller](https://user-images.githubusercontent.com/64943687/81943946-a6ed0780-95c1-11ea-9a54-566a65382ddf.jpg)

**Comment by Hax4us** [comment]
Run msfconsole and check if you can access sdcard or not

**Comment by HaroldLimad** [comment]
permission denied😿

**Comment by HaroldLimad** [comment]
The error is on the line (PAYLOAD.APK).  Any solution?  Thank you
![Screenshot_2020-05-14-20-05-57-961_com miui notes](https://user-images.githubusercontent.com/64943687/82000711-ce25f200-961e-11ea-97e6-2976c327a6f4.jpg)

it's time to replace it with this

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

**Comment by HaroldLimad** [comment]
it's time to replace it with this

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

**Comment by HaroldLimad** [comment]
it's time to replace it with this
![Screenshot_2020-05-14-20-05-57-961_com miui notes](https://user-images.githubusercontent.com/64943687/82001120-fc580180-961f-11ea-9ee3-32e6569b1f7a.jpg)

**Comment by Hax4us** [comment]
this problem is app specific because i am not facing the same problem with any other apps
