### ISSUE TITLE
Malformed

### ISSUE THREAD

**Issue by rk649477** [Hax4us/Apkmod#5]
apkmod -b $HOME/app.apk -o $HOME LHOST=127.0.0.1 LPORT=1492
/data/data/com.termux/files/usr/bin/apkmod: line 132: bc: command not found
/data/data/com.termux/files/usr/bin/apkmod: line 132: [: 1: unary operator expected
[*] Binding /data/data/com.termux/files/home/app.apk
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Using APK template: /data/data/com.termux/files/home/app.apk
Error: Malformed version number string 2.4.0
Picked up _JAVA_OPTIONS: -Duser.home=/data/data/com.termux/files/home -Djava.io.tmpdir=/data/data/com.termux/files/usr/tmp
[*] Binded to /data/data/com.termux/files/home
$

**Comment by Hax4us** [comment]
check which version you are using by `apkmod -v`

**Comment by rk649477** [comment]
apkmod -v
/data/data/com.termux/files/usr/bin/apkmod: line 132: bc: command not found
/data/data/com.termux/files/usr/bin/apkmod: line 132: [: 1: unary operator
expected
1.2

**Comment by Hax4us** [comment]
rerun setup script and see if problem still exists or not

**Comment by rk649477** [comment]
Solved thanks
