### ISSUE TITLE
Bro it is not working today

### ISSUE THREAD

**Issue by karansharmahr** [Hax4us/Apkmod#50]
#
![Screenshot_2020-05-23-13-23-34-092_com termux](https://user-images.githubusercontent.com/63999241/82725214-069d8e00-9cf9-11ea-9fcd-85e2c23e9cff.jpg)

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by Hax4us** [comment]
How did you install metasploit ?

**Comment by karansharmahr** [comment]
It's working now bruh nd I installed it by pkg install metasploit now it doesn't use -a it only binds with -b

**Comment by Hax4us** [comment]
Yes now `-a` is enabled by default
