### ISSUE TITLE
Metasploit Problem Please Help...

### ISSUE THREAD

**Issue by JEEVAN656565** [Hax4us/Apkmod#52]
![Screenshot_20200524-222153_Termux](https://user-images.githubusercontent.com/43090482/82759978-43a77480-9e0e-11ea-9b39-a723c9cf6e02.jpg)
See this and please help me.
I have already downloaded metasploit using "pkg install unstable-repo"
                                                                                 "pkg install metasploit"
it has installed successfully.
Additional information
App :Color.apk

Thank you.

**Comment by Hax4us** [comment]
You are using it in wrong way. Did you follow steps of installation ?

**Comment by JEEVAN656565** [comment]
Oh yes.I used bash setup.sh for downloading

**Comment by JEEVAN656565** [comment]
I used bash setup.sh . For setuping

**Comment by Hax4us** [comment]
then use `apkmod` instead of `apkmod.sh`

**Comment by JEEVAN656565** [comment]
Bro i have not given access to the termux to access my sdcard.SO THE PROBLEM AS ARISED
