### ISSUE TITLE
Please check this out

### ISSUE THREAD

**Issue by Yuvi1808** [Hax4us/Apkmod#55]
![Screenshot_2020-05-29-15-22-44](https://user-images.githubusercontent.com/66117222/83247151-c2aafd00-a1c0-11ea-8c60-1cec6842147d.png)
Please tell me some solution

**Comment by Hax4us** [comment]
Do `apkmod -u` and see if error is there

**Comment by Yuvi1808** [comment]
After 3 hours 
![Screenshot_2020-05-29-18-24-31](https://user-images.githubusercontent.com/66117222/83261857-a9fb1100-a1d9-11ea-8f76-041d29d2c386.png)
What should I do brother??

**Comment by Yuvi1808** [comment]
It is working
