### ISSUE TITLE
can't bind apk, no such file or directory

### ISSUE THREAD

**Issue by Ryuuzu1** [Hax4us/Apkmod#57]
![Screenshot_20200603-171254](https://user-images.githubusercontent.com/65439566/83625054-8f4fe000-a5bd-11ea-9a6b-40e558580689.jpg)

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by Hax4us** [comment]
Hii sorry for inconvenience. Can you reinstall apkmod with `apkmod -u --with-alpine` and see if error is there or not

**Comment by Ryuuzu1** [comment]
theres is no /.bind/payload.apk bro

**Comment by Ryuuzu1** [comment]
it happen when i reinstall apkmod

**Comment by Hax4us** [comment]
Yes try `apkmod -u --with-alpine` command

**Comment by Ryuuzu1** [comment]
thanks a lot bro, its work, keep ur awesome work

**Comment by Ryuuzu1** [comment]
bro, how to use --enable-perm

**Comment by Hax4us** [comment]
`apkmod --enable-perm=yourapp.apk -o output.apk`
