### ISSUE TITLE
unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by Abhishek653** [Hax4us/Apkmod#60]
what can i do now ? 🤒🤒🤒

**Comment by Hax4us** [comment]
Screenshot ?

**Comment by andifoza** [comment]
![Screenshot_20200622-205741_Termux](https://user-images.githubusercontent.com/65265922/85296184-35ab4900-b4cb-11ea-8d3f-c2a92380d11c.jpg)
Why ? Help me please

**Comment by Hax4us** [comment]
@andifoza it's app specific problem i can't do anything.
You will have to change your app
