### ISSUE TITLE
it's not working

### ISSUE THREAD

**Issue by rahimtony** [Hax4us/Apkmod#61]
![Screenshot_20200609_073335](https://user-images.githubusercontent.com/47412418/84098150-1c62c100-aa24-11ea-81b2-8424130d36b5.jpg)

**Comment by karansharmahr** [comment]
The tool is not correctly install just type the command to update 


apkmod -u

**Comment by Hax4us** [comment]
As @karansharmahr said it's not correctly installed so do `apkmod -u`

**Comment by karansharmahr** [comment]
Hey buddie im also a youtuber

**Comment by andifoza** [comment]
Use other apk
