### ISSUE TITLE
permissions problem !

### ISSUE THREAD

**Issue by hichemkanon** [Hax4us/Apkmod#62]
brother plz help me 
if we install the payload without bind it with anouther apk we will get full access to the phone with automatically granting permissions 

but when we bind payload into original apk we don't get the granted permissions automatic but it must the victim go to apk settings and manually allow the permisions 

so my question ; what we need to change for get an automatic allowing the permissions after binding the payload ???

**Comment by Hax4us** [comment]
Did you tried `apkmod --enable-perm=binded.apk -o newbinded.apk` ?

**Comment by hichemkanon** [comment]
> Did you tried `apkmod --enable-perm=binded.apk -o newbinded.apk` ?

No btothet i didn't try that ! 
I will try and tell you the result

Thakd so much bro, yiu arr always ready to help me or anothet 🌹

**Comment by Hax4us** [comment]
See https://www.hax4us.com/2020/06/enable-android-permissions.html?m=1

**Comment by hichemkanon** [comment]
brother sorry for this out topic question, but really i searched any where and did not found answer or solution 
you have experience i hope you help me 

for append text to file using shell command we use echo "newline" >> /sdcard/file.txt

but the line i want to adding is line with symbols "{data: "0..."(..)..=.." so the command echo will corrupt and doesnt work
what i need to do for appending a line with symbols to a file ??
i thank you brother in advance
