### ISSUE TITLE
Msfvenom not found

### ISSUE THREAD

**Issue by Shubhendra-kushwaha** [Hax4us/Apkmod#7]
/data/data/com.termux/files/usr/bin/apkmod: 101: /data/data/com.termux/files/usr/bin/apkmod: msfvenom: not found
![Screenshot_20190929_110351](https://user-images.githubusercontent.com/37535104/65826852-4cf53700-e2a9-11e9-879e-5946a4e84f65.jpg)

**Comment by Hax4us** [comment]
Install metasploit first

**Comment by Shubhendra-kushwaha** [comment]
> Install metasploit first from https://GitHub.com/Hax4Us/Metasploit_termux

I have already installed Metasploit Framework

**Comment by Hax4us** [comment]
Then it's not properly installed , you can check by creating payload by `msfvenom`

**Comment by Shubhendra-kushwaha** [comment]
> Then it's not properly installed , you can check by creating payload by `msfvenom`

I checked everything is working properly in metasploit

**Comment by Hax4us** [comment]
give screenshot while creating payload by msfvenom
