### ISSUE TITLE
I am not able to figure out what went wrong pls help

### ISSUE THREAD

**Issue by StrangeJackle** [Hax4us/Apkmod#85]
![IMG_20200821_212911.jpg](https://user-images.githubusercontent.com/50201223/90911419-946f3f00-e3f6-11ea-998b-9a87de415171.jpg)

**Comment by Hax4us** [comment]
Try latest Apkmod ( With latest apktool & aapt2 Support upto Android 11)

Installation Instructions

1. `wget https://raw.githubusercontent.com/Hax4us/Apkmod/aapt2-a11/setup.sh`

2. `sh setup.sh`

Its not for production use so you may expect some errors but don't forget to report back for quick fix
