### ISSUE TITLE
I have got a issue while rebuilding the apk.the error was "unable to rebuild the apk with apk tool".

### ISSUE THREAD

**Issue by beinghacker123456** [Hax4us/Apkmod#86]
![Screenshot_2020-08-26-01-40-08-25_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/68769104/91223094-bc83d880-e73d-11ea-9cd5-2c9bad63fb74.jpg)

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by Hax4us** [comment]
Try latest Apkmod ( With latest apktool & aapt2 Support upto Android 11)

Installation Instructions

1. `wget https://raw.githubusercontent.com/Hax4us/Apkmod/aapt2-a11/setup.sh`

2. `sh setup.sh`

Its not for production use so you may expect some errors but don't forget to report back for quick fix
