### ISSUE TITLE
Apk Recompile Error

### ISSUE THREAD

**Issue by MrSp4rX** [Hax4us/Apkmod#89]
**Problem description**
The problem is after decompiling the apk its not recompiling again

**Steps to reproduce**
I think apkmod should be upgraded with all new types of apps..

**Expected behavior**
I was expecting that it will compile my apk and then I cam easily use that app but it wasn't.

**Additional information**
1. apkmod -V -R termux -o termux.apk
[*] Recompiling /storage/emulated/0/app_work/Decompiled_Apps/termux
Sep 28, 2020 9:11:00 AM brut.androlib.Androlib build
INFO: Using Apktool 2.4.1
Sep 28, 2020 9:11:01 AM brut.androlib.Androlib buildSourcesSmali
INFO: Checking whether sources has changed...
Sep 28, 2020 9:11:01 AM brut.androlib.Androlib buildSourcesSmali
INFO: Smaling smali folder into classes.dex...
../../../../../sdcard/app_work/Decompiled_Apps/termux/smali/com/termux/app/TermuxActivity.smali[1774,28] Error for input '/': Invalid text
../../../../../sdcard/app_work/Decompiled_Apps/termux/smali/com/termux/app/TermuxActivity.smali[1774,39] Error for input '/': Invalid text
../../../../../sdcard/app_work/Decompiled_Apps/termux/smali/com/termux/app/TermuxActivity.smali[1774,29] mismatched input 'metasploit' expecting OPEN_PAREN
../../../../../sdcard/app_work/Decompiled_Apps/termux/smali/com/termux/app/TermuxActivity.smali[1774,45] Error for input '/': Invalid text
../../../../../sdcard/app_work/Decompiled_Apps/termux/smali/com/termux/app/TermuxActivity.smali[1774,54] no viable alternative at input '->'
Could not smali file: com/termux/app/TermuxActivity.smali
[!] Try again with -a option
But if still can't recompile, take screenshot and open a issue on github
2. Apkmod Version 2.2
3. 
![Screenshot_2020-09-28-14-36-42-51](https://user-images.githubusercontent.com/71897067/94413551-dbd8b000-0198-11eb-8ecd-15ba8cc78f5d.jpg)

**Comment by Hax4us** [comment]
i will look into your issue after **OCTOBER** ( because of exams )

**Comment by MrSp4rX** [comment]
> i will look into your issue after **OCTOBER** ( because of exams )

sure

**Comment by Hax4us** [comment]
Try latest Apkmod ( With latest apktool & aapt2 Support upto Android 11)

Installation Instructions

1. `wget https://raw.githubusercontent.com/Hax4us/Apkmod/aapt2-a11/setup.sh`

2. `sh setup.sh`

Its not for production use so you may expect some errors but don't forget to report back for quick fix
