### ISSUE TITLE
Some files in your server are missing

### ISSUE THREAD

**Issue by reynold02** [Hax4us/Apkmod#9]
![Screenshot_20190929-105534_Termux](https://user-images.githubusercontent.com/20007264/65835106-da378c00-e2a7-11e9-8a04-b49db66b43df.jpg)
After doing the install, it gives error 404 in msfvenom.patch and payload_generator
rb during receiving it from your github. I reinstall 3 times and nothing fixed. I even tried to execute the apkmod command with and without -a argument. It seems to be a little problem with missing files in your github, I hope this get solve soon, Thanks for this program by the way!

**Comment by Hax4us** [comment]
Now fixed with https://github.com/Hax4us/Apkmod/commit/850aa0a28c9ca26d1a65ddb705f72106afab046d
Rerun setup script
