### ISSUE TITLE
Unable to bind paylaod

### ISSUE THREAD

**Issue by whitedevil-o** [Hax4us/Apkmod#90]
![Screenshot_20201017-074833](https://user-images.githubusercontent.com/72953654/96326399-e2e33780-104d-11eb-8709-75850911dac7.png)
![Screenshot_20201017-074833](https://user-images.githubusercontent.com/72953654/96326403-e8d91880-104d-11eb-9466-6061be55f799.png)
![Screenshot_20201016-061810](https://user-images.githubusercontent.com/72953654/96326406-eaa2dc00-104d-11eb-9650-44ef62adbfbf.png)

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by Hax4us** [comment]
do `apkmod -u` & give all Screenshots here

**Comment by whitedevil-o** [comment]
Bhai ye problem arhi metasploit install karne me
