### ISSUE TITLE
Unable to bind paylaod 

### ISSUE THREAD

**Issue by whitedevil-o** [Hax4us/Apkmod#93]
![Screenshot_20201025-193534](https://user-images.githubusercontent.com/72953654/97109619-3adb0780-16fa-11eb-9e60-487f55f902c9.png)

**Comment by whitedevil-o** [comment]
plz fix

**Comment by Hax4us** [comment]
Try latest Apkmod

Installation Instructions

1. `wget https://raw.githubusercontent.com/Hax4us/Apkmod/aapt2-a11/setup.sh`

2. `sh setup.sh`

Its not for production use so you may expect some errors but don't forget to report back for quick fix
