### ISSUE TITLE
Unable to bind apk

### ISSUE THREAD

**Issue by paulush722** [Hax4us/Apkmod#99]
![Screenshot_2020-11-16-09-33-34-607_com termux](https://user-images.githubusercontent.com/64792130/99211758-1fda4f80-27ef-11eb-8d29-ea493620de22.jpg)

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
1. Post output of command `termux-info`
2. Post version `apkmod -v`
3. Attach Original __Apk__ file.

**Comment by VALIANTTH0R** [comment]
![Screenshot_2020-11-16-20-31-06-272_com termux](https://user-images.githubusercontent.com/74552871/99269266-2c40c580-284c-11eb-8f6d-b0fb564b311a.jpg)







This is my issue please tell me how to fix this.Reply me on my this gmail id :- dr.midside@gmail.com

**Comment by Hax4us** [comment]
@VALIANTTH0R u don't have metasploit installed.
@paulush722 your installation is broken and by the way you should try latest apkmod ( with latest aapt2 support upto android 11)

Installation Instructions

1) `wget https://raw.githubusercontent.com/Hax4us/Apkmod/aapt2-a11/setup.sh`

2) `sh setup.sh`

Its not for production use so you may expect some errors but don't forget to report back for quick fix
